#!/usr/bin/env bash
#File: tk.sh
#Time: 2023/11/14 09:22:21
#Author: Felix
#Desc: None

set -Eeuo pipefail
snd=""
minsnd=""
secsnd=""

usage(){
  echo -e "\tNowtime: $(date +"%F %T")"
  printf "\tUsage:   %s 10[h|m|s] default add suffix s means seconds\n " "$0"
  echo -e "\tExample: $0 10[h|m|s] default no sufiix,indicate seconds"
  echo -e "\tExample: $0 18:00:00"
  exit 1
}

alert(){
  title=""
  if [ "$#" -ge 2 ];then
    title="$2"
  fi
  sleep "$1"
  osascript -e "display notification \"$title 约定时间到，请注意\" with title \"TK提醒\""
  exit 0
}

validargs(){
  snd=""
  sndtmp=""
  if [[ "$#" -lt 1 ]];then
    kill -9 $(ps aux|grep "[l]ocalbin/tk \s*"|awk '{print $2}'|tr '\n' ' ') &>/dev/null && exit 0 || usage
  else
    if [[ "$1" =~ .*(h|m|s)$ ]];then
      if [[ "$1" == *h* ]];then
        hour="${1%h*}"
        snd="$((hour*60*60))"
      fi
      if [[ "$1" == *m*  ]]; then
        min="${1%m*}"
        min="${min#*h}"
        snd="$((snd+min*60))"
      fi
      if [[ "$1" == *s* ]];then
        sec="${1#*m}"
        sec="${sec#*h}"
        sec="${sec%s*}"
        snd="$((snd+sec))"
      fi
    else
      if [[ "$1" == *:* ]];then
        colonnu="$(echo "$1" |awk -F: '{print NF-1}')"
        if [ "$colonnu" -eq 2 ];then
            sndtmp="$(($(date -j -f "%H:%M:%S" "${1}" "+%s")-$(date +%s)))"
        fi 
        if [ "$colonnu" -eq 1 ];then
            sndtmp="$(($(date -j -f "%H:%M" "${1}" "+%s")-$(date +%s)))"
        fi
        if [[ "$sndtmp" -ge 0 ]];then
          snd="$sndtmp"
          minsnd="$((snd/60))"
          secsnd="$((snd%60))"
        else
          usage
        fi
      else
        snd="$1"
      fi
    fi
  fi
  echo "提醒时间为： $(date -v +"${snd}"S +"%F %T")"
  if [[ -n "$minsnd" ]];then
    echo "距离目前提醒时间： ${minsnd}分${secsnd}秒"
  fi 
  if [[ "$#" -lt 2 ]];then
    alert "$snd" &
  else
    alert "$snd" "$2" &
  fi
}

main(){
  validargs "$@"
}
main "$@"


